# Generated by Django 6.0.1 on 2026-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
